export const dayNames = ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс']

export const calendarCellsData = [
	{ day: 28, otherMonth: true },
	{ day: 29, otherMonth: true },
	{ day: 30, otherMonth: true },
	{ day: 31, otherMonth: false },
	{ day: 1, otherMonth: false },
	{ day: 2, otherMonth: false, isWeekend: true },
	{ day: 3, otherMonth: false, isWeekend: true },
	{ day: 4, otherMonth: false },
	{ day: 5, otherMonth: false },
	{ day: 6, otherMonth: false },
	{ day: 7, otherMonth: false },
	{ day: 8, otherMonth: false, isCurrent: true },
	{ day: 9, otherMonth: false, isWeekend: true, isActive: true },
	{ day: 10, otherMonth: false, isWeekend: true },
	{ day: 11, otherMonth: false },
	{ day: 12, otherMonth: false },
	{ day: 13, otherMonth: false },
	{ day: 14, otherMonth: false },
	{ day: 15, otherMonth: false },
	{ day: 16, otherMonth: false, isWeekend: true },
	{ day: 17, otherMonth: false, isWeekend: true },
	{ day: 18, otherMonth: false },
	{ day: 19, otherMonth: false },
	{ day: 20, otherMonth: false },
	{ day: 21, otherMonth: false },
	{ day: 22, otherMonth: false },
	{ day: 23, otherMonth: false, isWeekend: true },
	{ day: 24, otherMonth: false, isWeekend: true },
	{ day: 25, otherMonth: false },
	{ day: 26, otherMonth: false },
	{ day: 27, otherMonth: false },
	{ day: 28, otherMonth: false },
	{ day: 29, otherMonth: false },
	{ day: 30, otherMonth: false, isWeekend: true },
	{ day: 1, otherMonth: true, isWeekend: true },
]
